import './globals.css'

export const metadata = {
  title: 'Pecgo Test',
  description: 'Generated by Chayangkul',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        >{children}</body>
    </html>
  )
}
